apiVersion: v1
kind: Pod
metadata:
  name: finder-demo
  namespace: default
spec:
  containers:
  - name: finder-demo-ctr
    image: finder:1.2
    env:
      - name: config_name
        value: "stress_pod_memory.yml"
      - name: start_memory_value
        value: "200"
      - name: step_memory
        value: "100"
      - name: step_memory
        value: "60"
      - name: start
        value: "0"


    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap


