apiVersion: v1
kind: Pod
metadata:
  name: finder-demo
  namespace: default
spec:
  containers:
  - name: finder-demo-ctr
    image: finder:9.0
    env:
      - name: config_name
        value: "Hello_from_the_environment"
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap
        items:
          - key: stress_pod_memory.yml
            path: keys

